version: "3.4"

services:
    db:
      image: kartoza/postgis:13.0
      ports:
        - 5432:5432
      restart: always
      volumes:
         - ./posgis-data:/var/lib/postgresql
      environment:
        - POSTGRES_DB=gis
        - POSTGRES_USER=namdd
        - POSTGRES_PASS=13256789

    geoserver:
      image: kartoza/geoserver:2.18.0
      ports:
        - 8080:8080
      restart: always
      volumes:
          - ./geoserver-data:/opt/geoserver/data_dir
      environment:
        - DB_BACKEND=POSTGRES
        - HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_DB=gis
        - POSTGRES_USER=namdd
        - POSTGRES_PASS=13256789
        - GEOSERVER_ADMIN_USER=namdd
        - GEOSERVER_ADMIN_PASSWORD=13245