version: "3.4"

services:
    db:
      image: kartoza/postgis:13.0
      ports:
        - ${POSGRES_PORT}:5432
      restart: always
      volumes:
         - ./posgis-data:/var/lib/postgresql
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}

    geoserver:
      image: kartoza/geoserver:2.18.0
      ports:
        - ${GEOSERVER_PORT}:8080
      restart: always
      volumes:
          - ./geoserver-data:/opt/geoserver/data_dir
      environment:
        - DB_BACKEND=POSTGRES
        - HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}